### ISSUE TITLE
[BACK] Gestion des erreurs - data not found + class validator

### ISSUE THREAD

**Issue by MarieLouLeJan** [WildCodeSchool/2309-wns-jaune-eco-voit#48]
```[tasklist]
### Tasks
- [x] correction des tests qui failed depuis le hash password
- [x] Clean de la gestions des erreurs - data not found
- [x] Ajout décorateur class validator
- [x] Throw class validator errors
```

**Comment by MarieLouLeJan** [comment]
PR: https://github.com/WildCodeSchool/2309-wns-jaune-eco-voit/pull/60
