### ISSUE TITLE
[PITCH] Ajouter des screen à la présentation (voir détails dans l'us)

### ISSUE THREAD

**Issue by MarieLouLeJan** [WildCodeSchool/2309-wns-jaune-eco-voit#53]
```[tasklist]
### Tasks
- [ ] Ajouter des screens des diagrammes de class
- [ ] Ajouter des screens de tests
- [ ] Ajouter des screens entité, resolver, service ?
- [ ] Ajouter des screen de diagramme de séquence
```

```[tasklist]
### Tasks
```
